import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";
import AuthProvider from "@/AuthProvider";
import { Toaster } from "react-hot-toast";

import { ReduxProvider } from "@/redux-provider";
import Footer from "@/components/footer";
import dark from '../../public/dark.svg'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Buyer's Edge Ecommarce WebApp",
  description: "Generated by create next app",
  icons:dark
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <ReduxProvider>
              <Navbar />
              {children}
              <Footer/>
              <Toaster />
            </ReduxProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
